// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYfBOqyCdLOJn4pXW584Wc5lTGohQt4Xg',
    appId: '1:795564018597:web:ef2792fc7848078f6bb64c',
    messagingSenderId: '795564018597',
    projectId: 'serendipity-f3f75',
    authDomain: 'serendipity-f3f75.firebaseapp.com',
    storageBucket: 'serendipity-f3f75.firebasestorage.app',
    measurementId: 'G-NJFQWP0Q3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtMWezaSHGFmAVw8-YB4O7I-oHEBjrsc',
    appId: '1:795564018597:android:67afa730d8b1e51d6bb64c',
    messagingSenderId: '795564018597',
    projectId: 'serendipity-f3f75',
    storageBucket: 'serendipity-f3f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91RIvqmdRl9x5TVcDIZC2GLn1aGo4hT8',
    appId: '1:795564018597:ios:dbd4118ee55e4ef16bb64c',
    messagingSenderId: '795564018597',
    projectId: 'serendipity-f3f75',
    storageBucket: 'serendipity-f3f75.firebasestorage.app',
    iosBundleId: 'com.serendipity.serendipityApp',
  );
}

